hlp:
  services:
    webapi-gateway:
      host: localhost
    user-service:
      host: localhost
    order-service:
      host: localhost
    config-server:
      host: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
